### ISSUE TITLE
Can't start with kong 0.9.0 (or "next") 

### ISSUE THREAD

**Issue by Diwann** [Mashape/kong-vagrant#19]
After a kong update from 0.8.3 to 0.9.0 (or a fresh install with 0.9.0), the vagrant kong host can't start: 

> vagrant@precise64:/kong$ kong start --trace
> Error:
> ./kong/cmd/start.lua:15: connection refused
> stack traceback:
>        	[C]: in function 'assert'
>        	./kong/cmd/start.lua:15: in function 'cmd_exec'
>        	./kong/cmd/init.lua:81: in function <./kong/cmd/init.lua:81>
>        	[C]: in function 'xpcall'
>        	./kong/cmd/init.lua:81: in function <./kong/cmd/init.lua:42>
>       	/usr/local/bin/kong:11: in function 'file_gen'
>       	init_worker_by_lua:38: in function <init_worker_by_lua:36>
>       	[C]: in function 'pcall'
>       	init_worker_by_lua:45: in function <init_worker_by_lua:43>

**Comment by Tieske** [comment]
This usually indicates the database is unavailable. Make sure to have the proper settings and the db available (and reachable)

**Comment by Tieske** [comment]
If you can't get it running, try setting the environment variables to configure it instead of a config file.

**Comment by Diwann** [comment]
But if I switch back to kong 0.8.3, it works fine... 
(`git co 0.8.3` on my host, and `sudo make dev` on the vagrant machine)

**Comment by Diwann** [comment]
maybe linked to : https://github.com/Mashape/kong/issues/1543 ?

**Comment by Diwann** [comment]
Ok, it's most probably linked to: 
"⚠️ PostgreSQL is the new default datastore for Kong. If you were using Cassandra and you are upgrading, you need to explicitly set cassandra as your database." as no database was defined by default in the /etc/kong/kong.conf file (which was not created). 
Again, this is with a fresh install of kong following this readme: https://github.com/Mashape/kong-vagrant
