### ISSUE TITLE
git is missing in the vagrant box 

### ISSUE THREAD

**Issue by tyiss** [Mashape/kong-vagrant#2]
some libraries, specifically lua-cassandra depend on git.
the base vagrant box is missing git.

<pre>
vagrant@precise64:~$ cd /kong
vagrant@precise64:/kong$ sudo make dev

Missing dependencies for kong:
lua-cassandra ~> 0.3.5-0

Using https://luarocks.org/lua-cassandra-0.3.5-0.rockspec... switching to 'build' mode
sh: 1: git: not found

</pre>

i think a the fix should include update to the box to ubunto 14.04.
i've tested with:
<pre>
config.vm.box = "puphpet/ubuntu1404-x64"
</pre>

let me know if you create PR for it.

**Comment by ahmadnassri** [comment]
PRs are always welcome :+1:

**Comment by dougbeauchene** [comment]
may also want to include "curl" for convenience since the README info at https://github.com/Mashape/kong-vagrant has the user run a curl command.

**Comment by thibaultCha** [comment]
No the curl command is supposed to be run from the Guest OS.

**Comment by thibaultCha** [comment]
(now included :+1:)
