### ISSUE TITLE
Startup process changes in 0.9.x versions

### ISSUE THREAD

**Issue by logronoide** [Mashape/kong-vagrant#20]
It seems that the newest versions of Kong now starts up in a different way. The command to start the kong service is described as follows:

```
# start Kong
$ kong start -c kong_DEVELOPMENT.yml
```

but the kong_DEVELOPMENT.yml is not created now, and may be it's not necessary anymore. As result, Kong does not start.

To start Kong I had to follow these steps:

1. Copy the file /etc/kong/kong.conf.default to /etc/kong/kong.conf
1. Edit the /etc/kong/kong.conf file and add the entry `database = cassandra`
1. Now start Kong without the -c parameter:

```
vagrant@precise64:/kong$ kong start 
```

If you want to configure new plugins, there is a parameter in the kong.conf file called `custom_plugins`

**Comment by thefosk** [comment]
Fixed.
