### ISSUE TITLE
kong start command throws error: could not find OpenResty 

### ISSUE THREAD

**Issue by skyserpent** [Mashape/kong-vagrant#27]
Here is a gist of the verbose output:

[https://gist.github.com/skyserpent/d6d03565e7c2a5f3fda29a21caa6b5a3](https://gist.github.com/skyserpent/d6d03565e7c2a5f3fda29a21caa6b5a3)

**Comment by Tieske** [comment]
Kong tries a number of default paths to locate the `resty` executable

> 2016/12/06 06:52:10 [verbose] 'resty' found at /usr/local/openresty/bin/resty uses incompatible OpenResty. Kong requires OpenResty version 1.11.2.1, got 1.9.15.1

So here it finds one, but it's the wrong version


> 2016/12/06 06:52:10 [debug] resty -V: 'sh: 1: resty: not found'
2016/12/06 06:52:10 [debug] OpenResty 'resty' executable not found at resty

next it tries calling just the executable (relying on the system path) but doesn't find it.

Then it is out of options and fails.

So where is openresty on your system?

**Comment by skyserpent** [comment]
Am I supposed to have OpenResty on the host or guest machine? I would
assume the kong-vagrant would handle all that.

**Comment by Tieske** [comment]
my bad, didn't notice this was on the vagrant repo.

Anyway, fixed it. See the [added troubleshooting entry](https://github.com/Mashape/kong-vagrant#incompatible-versions-error) in the readme.

**Comment by skyserpent** [comment]
Thanks @Tieske!
