### ISSUE TITLE
make test-all

### ISSUE THREAD

**Issue by frank-montyne** [Mashape/kong-vagrant#30]
After installing the kong-vagrant environment I ran "make dev" and I could start kong successfully.

When running make test-all I get the following error:

make test-all
/usr/bin/env: resty: No such file or directory
make: *** [test-all] Error 127

Any ideas?

**Comment by frank-montyne** [comment]
Apparently the path was missing the following entry /usr/local/openresty/bin

Now I get the following error when running make test-all:

...
Failure → spec/02-integration/02-dao/02-migrations_spec.lua @ 86
Model migrations with DB: #postgres [INTEGRATION] should not run any migration on subsequent run
spec/02-integration/02-dao/02-migrations_spec.lua:91: Expected to be falsy, but value was:
(string) '[postgres error] FATAL: database "kong_tests" does not exist'

stack traceback:
	spec/02-integration/02-dao/02-migrations_spec.lua:91: in function <spec/02-integration/02-dao/02-migrations_spec.lua:86>


Failure → spec/02-integration/02-dao/02-migrations_spec.lua @ 18
Model migrations with DB: #cassandra current_migrations() should return an empty table if no migrations have been run
spec/02-integration/02-dao/02-migrations_spec.lua:20: Expected to be falsy, but value was:
(table) {
  [db] = true
  [message] = 'All hosts tried for query failed. 127.0.0.1: connection refused for socket with peer 127.0.0.1.' }

stack traceback:
	spec/02-integration/02-dao/02-migrations_spec.lua:20: in function <spec/02-integration/02-dao/02-migrations_spec.lua:18>
...

**Comment by JnMik** [comment]
Here's all I had to do in order to have the VM working with the project (running virtual box on windows)

- Download kong-vagrant
- make sur kong folder is located at the same level of your kong-vagrant (and make sure that line endings is in LF)
- in the kong-vagrant folder, vagrant up --provision && vagrant ssh to boot and get into the VM
- export PATH=/usr/local/openresty/bin:$PATH
- cd /home/vagrant
- ln -sfn /usr/local .luarocks
- cd /kong
- make dev
- sudo -u postgres createdb -O kong kong_tests
- sudo apt-get install redis-server
- sudo chown vagrant /var/log/redis/redis-server.log
- make test-plugins
- kong start
- curl http://localhost:8001

**Comment by JnMik** [comment]
Also I had a weird DNS issue at some time, having the resolv.conf nameserver pointing to 127.0.0.1 wasn't working for me. With nameserver 8.8.8.8 it was working tho, so I didn't really investigate more and added some code in provision.sh lol

```
# Bug fix DNS issue
sudo bash -c "cat > /etc/resolv.conf" << EOL
nameserver 8.8.8.8
EOL
```

I won't do a pull request for it tho, i'm probably the only one that had such a hard time configuring it.
Tbh,  I expected a bit more of "Plug-n-play" VM.

Tell me if it helps you !

**Comment by Tieske** [comment]
@frank-montyne I made some updates, did they fix your issues?

- path is now properly exported
- dns issue

**Comment by frank-montyne** [comment]
Unfortunately I'm working on another project that has a very tight deadline. I will come back to this but not before the end of February. I'll check if the issues are fixed at that point and give some feedback then.
Best regards,
Frank

**Comment by JnMik** [comment]
I've added two other PRs that may be necessary to make the environment works correctly.
https://github.com/Mashape/kong-vagrant/pull/34
https://github.com/Mashape/kong-vagrant/pull/33

**Comment by Tieske** [comment]
Merged most of those (in some form), also added the cassandra installation. That should complete the development environment.

Closing this. Feel free to reopen if the problems persist.
