### ISSUE TITLE
sudo make dev   fails on Windows 7 host

### ISSUE THREAD

**Issue by dougbeauchene** [Mashape/kong-vagrant#4]
I am able to run all the steps up to "sudo make dev" to set up on my Windows 7 host.

When I run the make step it yields...
  bin/kong config -c kong.yml -e TEST
  : No such file or directory 
  make: *** [dev] Error 127

If I try to run "bin/kong" manually I get the same error as the make displays.

If I "cd bin" to go into the bin directory where the "kong" executable is and run kong manually I get...
  vagrant@precise64:/kong/bin$ kong
  Missing <command>

  Usage: kong <command>

    where <command> is one of:
      start, restart, reload, stop, quit, version

    kong --help            print this message
    kong <command> --help  print the help message of a command

  kong@0.4.2-1

I have tried changing the formatting ( ie use of / vs \ ) of my "KONG_PATH" environment variable in Windows and it has no effect.

Any ideas what may be wrong with my Windows host environment?

**Comment by tyiss** [comment]
after you ssh to the machine by running 
vagrant ssh
do you see files at /kong (what is the output of 'ls /kong') ?
maybe you've entered incorrect path to KONG_PATH  ?

**Comment by dougbeauchene** [comment]
From vagrant ssh /kong has all the files from what I clomed on my windows host. KONG_PATH seems to have been set correctly. 

I can "cd bin" and see the kong  lua file just fine. 

But it can't be executed. 

Could it be something with the shebang line in kong where lua isn't being found?

**Comment by dougbeauchene** [comment]
My colleague did the same setup on his Windows 7 host and sees the same issue.

**Comment by dougbeauchene** [comment]
From my "vagrant ssh" session, I cd into /kong/bin

I can see the "kong" lua file.

If I flip over to Windows and create a new file in /kong/bin I can see that new file in my "vagrant ssh" session.  So it seems the ssh session is mapping the folder from my Windows host.

From my "vagrant ssh" session, if I cd into /kong/bin where the "kong" lua file is, when I run "which kong" it returns....
   vagrant@precise64:/kong/bin$ which kong
   /usr/local/bin/kong

If try to run kong from within /kong/bin, it runs /usr/local/bin/kong....not the one in my /kong/bin directory.

ls -l of /kong/bin returns....
    vagrant@precise64:/kong/bin$ ls -l
    total 2
    -rwxrwxrwx 1 vagrant vagrant 1551 Aug 19 20:06 kong

**Comment by dougbeauchene** [comment]
Worked around the issue by updating 3 lines in the Makefile dev section to prepend the invoke of bin/kong with   "/usr/bin/env lua "

example....

dev: install
	@for rock in $(DEV_ROCKS) ; do \
		if ! command -v $$rock &> /dev/null ; then \
      echo $$rock not found, installing via luarocks... ; \
      luarocks install $$rock ; \
    else \
      echo $$rock already installed, skipping ; \
    fi \
	done;
	/usr/bin/env lua bin/kong config -c kong.yml -e TEST
	/usr/bin/env lua bin/kong config -c kong.yml -e DEVELOPMENT
	/usr/bin/env lua bin/kong migrations -c $(DEVELOPMENT_CONF) up
