### ISSUE TITLE
control the memory of the vagrant machine from env variable

### ISSUE THREAD

**Issue by tyiss** [Mashape/kong-vagrant#6]
currently the virtual machine RAM is set as '2048'.
for some workstations its to much (slows the workstation), others could give more RAM to virtual machine.

instead of change the value in the Vagrant file, it will be nice to control it from outside.
for example set the RAM as 4G:
<pre>
KONG_PATH=/path/to//kong VB_MEM=4092 vagrant up
</pre>

**Comment by thefosk** [comment]
You can set the environment variable `KONG_VB_MEM`.
