### ISSUE TITLE
0.11.0 - Runtime error: plugins_iterator - attempt to index field 'cache' (a nil value)

### ISSUE THREAD

**Issue by hnq90** [Mashape/kong-vagrant#63]
I guest it's related to Vagrant's provisioning so I also create the issue here: https://github.com/Mashape/kong/issues/2838

I tried to run Kong from Docker and I didn't got this issue.

**Comment by Tieske** [comment]
did you by any chance disable the `lua_code_cache` directive? That is no longer supported.

**Comment by hnq90** [comment]
@Tieske Yes, I didn't set `lua_code_cache` and the above issue didn't occur. Thank you.
