### ISSUE TITLE
Doesnot work with xenial64

### ISSUE THREAD

**Issue by argentum47** [Mashape/kong-vagrant#66]
With ubuntu xenial64.
```
vagrant ssh -c "kong start --run-migrations"
prefix directory /usr/local/kong not found, trying to create it
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:19: Permission denied

  Run with --v (verbose) or --vv (debug) for more details
Connection to 127.0.0.1 closed.
```

Works with sudo though

**Comment by p0pr0ck5** [comment]
This is expected behavior. As the output indicates write permission to the parent of the Kong path is needed. If such a parent is owned by root, then Kong must prepare the prefix as root.

**Comment by p0pr0ck5** [comment]
Also, the provisioner script chowns /usr/local to the vagrant user. You will want to ensure this has actually taken place on your environment
