### ISSUE TITLE
detaulf ulimit value cause a warning in kong start

### ISSUE THREAD

**Issue by tyiss** [Mashape/kong-vagrant#9]
the dev machine default value for ulimit is 1024.
since this value is less then 4096, a warning is raised when kong start.

<pre>
vagrant@precise64:/kong$ kong start -c kong_DEVELOPMENT.yml 
...
...
[WARN] ulimit is currently set to "1024". For better performance set it to at least "4096" using "ulimit -n"
</pre>

**Comment by thefosk** [comment]
Closed via #26.

**Comment by Edenshaw** [comment]
I know it's closed, but for anyone this may help:

If you are using Ubuntu or Debian, go to the file: **/etc/security/limits.conf** and add the line (at the end)

`* 		soft 	nofile 		4096`

Save and test it by executing the command;

`ulimit -n 4096`

Restart Kong and check if you get the warning.
